In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("train.csv",usecols=['Age','Pclass','Fare','Survived'])

In [5]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [17]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [19]:
# we jnow that Age column has null value

In [25]:
x = df.drop(columns =['Survived'])
y =df['Survived']

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [33]:
x.head()

   Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500

In [71]:
knn = KNNImputer(n_neighbors=4)

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [73]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397

In [75]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [77]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978